[font]
size = 9.5

[window]
decorations = "none"
blur = true
opacity = 1
padding = { x = 5, y = 5 }
dynamic_padding = true

# (Github Light) Colors for Alacritty
[colors]
primary = { background = "#ffffff", foreground = "#1f2328" }

[colors.cursor]
cursor = "#1f2328"
text = "#ffffff"

# Normal colors
[colors.normal]
black = '#24292f'
red = '#cf222e'
green = '#116329'
yellow = '#4d2d00'
blue = '#0969da'
magenta = '#8250df'
cyan = '#1b7c83'
white = '#6e7781'

# Bright colors
[colors.bright]
black = '#57606a'
red = '#a40e26'
green = '#1a7f37'
yellow = '#633c01'
blue = '#218bff'
magenta = '#8250df'
cyan = '#1b7c83'
white = '#6e7781'
