;;; init.el --- Core Bootstrapper -*- lexical-binding: t; -*-

;; Restore normal GC performance threshold after Emacs is ready
(add-hook 'emacs-startup-hook
          (lambda ()
            (setq gc-cons-threshold (* 2 1024 1024))))

;; Set up package management repositories
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("elpa"  . "https://elpa.gnu.org/packages/")))
(package-initialize)

;; Bootstrap 'use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-repositories)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

;; Auto-install missing packages declared via use-package
(setq use-package-always-ensure t)

;; Compile and load the literate configuration file from config.org
(let ((literate-config (expand-file-name "config.org" user-emacs-directory)))
  (if (file-exists-p literate-config)
      (org-babel-load-file literate-config)
    (message "Warning: config.org file not found in %s" user-emacs-directory)))

;; Keep Emacs-generated Custom settings isolated from manually written configuration
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))




















































;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ;;; .emacs --- Optimized Emacs Configuration -*- lexical-binding: t; -*-                                                                                                                                                                                              ;;
;; ;;; Commentary:                                                                                                                                                                                                                                                       ;;
;; ;;; Built with Emacs best practices: lexical binding, garbage collection optimization,                                                                                                                                                                                ;;
;; ;;; structured use-package management, and deferred loading.                                                                                                                                                                                                          ;;
;; ;;; Includes automatic theme switching based on KDE daytime schedules, Magit, Org-mode,                                                                                                                                                                               ;;
;; ;;; Which-key, and robust LSP support for Python, JavaScript, HTML, and Ruff.                                                                                                                                                                                         ;;
;; ;;; Code:                                                                                                                                                                                                                                                             ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;; ;; 1. INITIALIZATION & PERFORMANCE OPTIMIZATION                                                                                                                                                                                                                       ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Optimize garbage collection thresholds during startup to reduce load time                                                                                                                                                                                          ;;
;; (setq gc-cons-threshold (* 50 1024 1024))                                                                                                                                                                                                                             ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Restore normal GC threshold after startup                                                                                                                                                                                                                          ;;
;; (add-hook 'emacs-startup-hook                                                                                                                                                                                                                                         ;;
;;           (lambda ()                                                                                                                                                                                                                                                  ;;
;;             (setq gc-cons-threshold (* 2 1024 1024))))                                                                                                                                                                                                                ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Avoid unnecessary UI flashing and native compilation warnings                                                                                                                                                                                                      ;;
;; (setq inhibit-startup-message t                                                                                                                                                                                                                                       ;;
;;       native-comp-async-report-warnings-errors 'silent)                                                                                                                                                                                                               ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Clean up the frame UI early for a distraction-free environment                                                                                                                                                                                                     ;;
;; (when (fboundp 'tool-bar-mode) (tool-bar-mode -1))                                                                                                                                                                                                                    ;;
;; (when (fboundp 'menu-bar-mode) (menu-bar-mode 1))                                                                                                                                                                                                                     ;;
;; (when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))                                                                                                                                                                                                                ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;; ;; 2. PACKAGE MANAGEMENT SETUP (use-package)                                                                                                                                                                                                                          ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (require 'package)                                                                                                                                                                                                                                                    ;;
;; (setq package-archives '(("melpa" . "https://melpa.org/packages/")                                                                                                                                                                                                    ;;
;;                          ("elpa"  . "https://elpa.gnu.org/packages/")))                                                                                                                                                                                               ;;
;; (package-initialize)                                                                                                                                                                                                                                                  ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Bootstrap 'use-package' if not already installed                                                                                                                                                                                                                   ;;
;; (unless (package-installed-p 'use-package)                                                                                                                                                                                                                            ;;
;;   (package-refresh-repositories)                                                                                                                                                                                                                                      ;;
;;   (package-install 'use-package))                                                                                                                                                                                                                                     ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (eval-when-compile                                                                                                                                                                                                                                                    ;;
;;   (require 'use-package))                                                                                                                                                                                                                                             ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Ensure all package declarations automatically install themselves                                                                                                                                                                                                   ;;
;; (setq use-package-always-ensure t)                                                                                                                                                                                                                                    ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;; ;; 3. THEME MANAGEMENT (ef-themes Collection & KDE Plasma 6 Integration)                                                                                                                                                                                              ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (use-package ef-themes                                                                                                                                                                                                                                                ;;
;;   :ensure t                                                                                                                                                                                                                                                           ;;
;;   :config                                                                                                                                                                                                                                                             ;;
;;   ;; Safely set your preferred light and dark pairs AFTER the package loads                                                                                                                                                                                           ;;
;;   (setq ef-themes-to-toggle '(ef-eagle ef-owl))                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;;   ;; Disable all other custom themes safely before parsing                                                                                                                                                                                                            ;;
;;   (mapc #'disable-theme custom-enabled-themes))                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (defun my/sync-theme-with-kde-6 ()                                                                                                                                                                                                                                    ;;
;;   "Query KDE Plasma 6 theme engine and map to light/dark ef-themes."                                                                                                                                                                                                  ;;
;;   (interactive)                                                                                                                                                                                                                                                       ;;
;;   (let* ((case-fold-search t) ; Enforce case-insensitive matching natively                                                                                                                                                                                            ;;
;;          (plasma6-scheme (shell-command-to-string "kreadconfig6 --group 'General' --key 'ColorScheme' 2>/dev/null"))                                                                                                                                                  ;;
;;          (xdg-scheme (shell-command-to-string "dbus-send --print-reply=literal --dest=org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read string:'org.freedesktop.appearance' string:'color-scheme' 2>/dev/null"))    ;;
;;          ;; Plasma 6 returns a value of 1 for dark preference in the portal specification                                                                                                                                                                             ;;
;;          (is-dark (or (string-match-p "dark" plasma6-scheme)                                                                                                                                                                                                          ;;
;;                       (string-match-p "uint32 1" xdg-scheme))))                                                                                                                                                                                                       ;;
;;     (if is-dark                                                                                                                                                                                                                                                       ;;
;;         ;; Match to the Dark theme entry (second element of ef-themes-to-toggle)                                                                                                                                                                                      ;;
;;         (let ((dark-theme (cadr ef-themes-to-toggle)))                                                                                                                                                                                                                ;;
;;           (unless (custom-theme-enabled-p dark-theme)                                                                                                                                                                                                                 ;;
;;             (mapc #'disable-theme custom-enabled-themes)                                                                                                                                                                                                              ;;
;;             (load-theme dark-theme t)))                                                                                                                                                                                                                               ;;
;;       ;; Match to the Light theme entry (first element of ef-themes-to-toggle)                                                                                                                                                                                        ;;
;;       (let ((light-theme (car ef-themes-to-toggle)))                                                                                                                                                                                                                  ;;
;;         (unless (custom-theme-enabled-p light-theme)                                                                                                                                                                                                                  ;;
;;           (mapc #'disable-theme custom-enabled-themes)                                                                                                                                                                                                                ;;
;;           (load-theme light-theme t))))))                                                                                                                                                                                                                             ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Evaluate when the layout interface engine initializes                                                                                                                                                                                                              ;;
;; (add-hook 'window-setup-hook #'my/sync-theme-with-kde-6)                                                                                                                                                                                                              ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Continuously query every 3 minutes to instantly track KDE daytime changes                                                                                                                                                                                          ;;
;; (run-at-time "3 min" 180 #'my/sync-theme-with-kde-6)                                                                                                                                                                                                                  ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;; ;; 4. CORE COMPONENT CONFIGURATIONS                                                                                                                                                                                                                                   ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; --- Magit ---                                                                                                                                                                                                                                                      ;;
;; (use-package magit                                                                                                                                                                                                                                                    ;;
;;   :commands magit-status                                                                                                                                                                                                                                              ;;
;;   :bind ("C-x g" . magit-status))                                                                                                                                                                                                                                     ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; --- Org Mode ---                                                                                                                                                                                                                                                   ;;
;; (use-package org                                                                                                                                                                                                                                                      ;;
;;   :defer t                                                                                                                                                                                                                                                            ;;
;;   :config                                                                                                                                                                                                                                                             ;;
;;   (setq org-ellipsis " ▾"                                                                                                                                                                                                                                             ;;
;;         org-hide-leading-stars t                                                                                                                                                                                                                                      ;;
;;         org-log-done 'time))                                                                                                                                                                                                                                          ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; --- Which Key ---                                                                                                                                                                                                                                                  ;;
;; (use-package which-key                                                                                                                                                                                                                                                ;;
;;   :init                                                                                                                                                                                                                                                               ;;
;;   (which-key-mode)                                                                                                                                                                                                                                                    ;;
;;   :config                                                                                                                                                                                                                                                             ;;
;;   (setq which-key-idle-delay 0.3))                                                                                                                                                                                                                                    ;;
;;                                                                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (setq-default indent-tabs-mode nil) ; Use spaces instead of tabs                                                                                                                                                                                                      ;;
;; (setq-default tab-width 4)          ; Set tab width to 4 spaces                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;; ;; 5. LSP & LANGUAGE SUPPORT (Python, Ruff, JS, HTML)                                                                                                                                                                                                                 ;;
;; ;; =============================================================================                                                                                                                                                                                      ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Common LSP Client (LSP-Mode)                                                                                                                                                                                                                                       ;;
;; (use-package lsp-mode                                                                                                                                                                                                                                                 ;;
;;   :commands (lsp lsp-deferred)                                                                                                                                                                                                                                        ;;
;;   :hook ((python-mode . lsp-deferred)                                                                                                                                                                                                                                 ;;
;;          (js-mode . lsp-deferred)                                                                                                                                                                                                                                     ;;
;;          (js2-mode . lsp-deferred)                                                                                                                                                                                                                                    ;;
;;          (typescript-mode . lsp-deferred)                                                                                                                                                                                                                             ;;
;;          (html-mode . lsp-deferred))                                                                                                                                                                                                                                  ;;
;;   :init                                                                                                                                                                                                                                                               ;;
;;   (setq lsp-keymap-prefix "C-c l")                                                                                                                                                                                                                                    ;;
;;   :config                                                                                                                                                                                                                                                             ;;
;;   (setq lsp-enable-indentation t                                                                                                                                                                                                                                      ;;
;;         lsp-diagnostics-provider :flycheck)                                                                                                                                                                                                                           ;;
;;   (lsp-enable-which-key-integration t))                                                                                                                                                                                                                               ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; Enhanced LSP UI features                                                                                                                                                                                                                                           ;;
;; (use-package lsp-ui                                                                                                                                                                                                                                                   ;;
;;   :commands lsp-ui-mode                                                                                                                                                                                                                                               ;;
;;   :hook (lsp-mode . lsp-ui-mode)                                                                                                                                                                                                                                      ;;
;;   :config                                                                                                                                                                                                                                                             ;;
;;   (setq lsp-ui-doc-enable t                                                                                                                                                                                                                                           ;;
;;         lsp-ui-sideline-enable t))                                                                                                                                                                                                                                    ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; --- Python & Ruff LSP Configuration ---                                                                                                                                                                                                                            ;;
;; ;; Configures lsp-mode to seamlessly orchestrate Ruff via python-lsp-server (pylsp)                                                                                                                                                                                   ;;
;; (use-package python                                                                                                                                                                                                                                                   ;;
;;   :mode ("\\\\.py\\'" . python-mode)                                                                                                                                                                                                                                  ;;
;;   :config                                                                                                                                                                                                                                                             ;;
;;   ;; Ensure python-lsp-server utilizes the ruff plugin                                                                                                                                                                                                                ;;
;;   (setq lsp-pylsp-plugins-ruff-enabled t                                                                                                                                                                                                                              ;;
;; 	lsp-pylsp-plugins-pyright-enabled t                                                                                                                                                                                                                                  ;;
;;         lsp-pylsp-plugins-flake8-enabled nil                                                                                                                                                                                                                          ;;
;;         lsp-pylsp-plugins-mccabe-enabled nil                                                                                                                                                                                                                          ;;
;;         lsp-pylsp-plugins-pycodestyle-enabled nil))                                                                                                                                                                                                                   ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; --- JavaScript Support ---                                                                                                                                                                                                                                         ;;
;; (use-package js                                                                                                                                                                                                                                                       ;;
;;   :mode ("\\\\.js\\'" . js-mode)                                                                                                                                                                                                                                      ;;
;;   :config                                                                                                                                                                                                                                                             ;;
;;   (setq js-indent-level 2))                                                                                                                                                                                                                                           ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; --- HTML Support ---                                                                                                                                                                                                                                               ;;
;; (use-package mhtml-mode                                                                                                                                                                                                                                               ;;
;;   :mode ("\\\\.html?\\'" . mhtml-mode))                                                                                                                                                                                                                               ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; --- Projects ---                                                                                                                                                                                                                                                   ;;
;; (global-set-key (kbd "C-<f9>") 'project-compile)                                                                                                                                                                                                                      ;;
;; (global-set-key (kbd "C-S-t") 'project-shell)                                                                                                                                                                                                                         ;;
;; (global-set-key (kbd "C-S-f") 'project-find-file)                                                                                                                                                                                                                     ;;
;; (global-set-key (kbd "C-S-g") 'project-find-regexp)                                                                                                                                                                                                                   ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; --- Helm(minibuffer)---                                                                                                                                                                                                                                            ;;
;; (require 'helm)                                                                                                                                                                                                                                                       ;;
;; (helm-mode 1)                                                                                                                                                                                                                                                         ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (setq helm-allow-mouse t)                                                                                                                                                                                                                                             ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (define-key global-map [remap list-buffers] 'helm-buffers-list)                                                                                                                                                                                                       ;;
;; (define-key global-map [remap execute-extended-command] 'helm-M-x)                                                                                                                                                                                                    ;;
;; (define-key global-map [remap find-file] 'helm-find-files)                                                                                                                                                                                                            ;;
;; (define-key global-map [remap switch-to-buffer] #'helm-mini)                                                                                                                                                                                                          ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (unless (boundp 'completion-in-region-function)                                                                                                                                                                                                                       ;;
;;   (define-key lisp-interaction-mode-map [remap completion-at-point] 'helm-lisp-completion-at-point)                                                                                                                                                                   ;;
;;   (define-key emacs-lisp-mode-map       [remap completion-at-point] 'helm-lisp-completion-at-point))                                                                                                                                                                  ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;;; I need arrow keys                                                                                                                                                                                                                                                 ;;
;; (customize-set-variable 'helm-ff-lynx-style-map t)                                                                                                                                                                                                                    ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;;; terminal like tabs selection                                                                                                                                                                                                                                      ;;
;; (define-key helm-map (kbd "<tab>") 'helm-next-line)                                                                                                                                                                                                                   ;;
;; (define-key helm-map (kbd "<backtab>") 'helm-previous-line)                                                                                                                                                                                                           ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;;; show command details                                                                                                                                                                                                                                              ;;
;; (define-key helm-map (kbd "<right>") 'helm-execute-persistent-action)                                                                                                                                                                                                 ;;
;; (define-key helm-map (kbd "<left>") 'helm-execute-persistent-action)                                                                                                                                                                                                  ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; programming > web > js                                                                                                                                                                                                                                             ;;
;; (add-to-list 'auto-mode-alist '("\\.mjs$" . js-mode))                                                                                                                                                                                                                 ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; folding                                                                                                                                                                                                                                                            ;;
;; (add-hook 'prog-mode-hook (lambda () (yafolding-mode)))                                                                                                                                                                                                               ;;
;; (add-hook 'compilation-mode-hook 'yafolding-mode)                                                                                                                                                                                                                     ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; ctrl z                                                                                                                                                                                                                                                             ;;
;; (global-unset-key (kbd "C-z")) ; unbind (suspend-frame)                                                                                                                                                                                                               ;;
;; ;; use undo-tree with ctrl-z                                                                                                                                                                                                                                          ;;
;; (require 'undo-tree)                                                                                                                                                                                                                                                  ;;
;; ;; (dim-minor-name 'undo-tree-mode "")                                                                                                                                                                                                                                ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (global-undo-tree-mode 1)                                                                                                                                                                                                                                             ;;
;; (setq undo-tree-visualizer-timestamps t)                                                                                                                                                                                                                              ;;
;; (setq undo-tree-visualizer-diff t)                                                                                                                                                                                                                                    ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; stop unde tree from saving *.~undo-tree~ everywhere                                                                                                                                                                                                                ;;
;; (setq undo-tree-auto-save-history nil)                                                                                                                                                                                                                                ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; region undo                                                                                                                                                                                                                                                        ;;
;; ;; (setq undo-tree-enable-undo-in-region t)                                                                                                                                                                                                                           ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; normal undo and redo                                                                                                                                                                                                                                               ;;
;; (global-set-key (kbd "C-z") 'undo-only)                                                                                                                                                                                                                               ;;
;; (global-set-key (kbd "C-S-z") 'undo-tree-redo)                                                                                                                                                                                                                        ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; line numbers                                                                                                                                                                                                                                                       ;;
;; (add-hook 'prog-mode-hook 'display-line-numbers-mode)                                                                                                                                                                                                                 ;;
;; (add-hook 'org-mode-hook 'display-line-numbers-mode)                                                                                                                                                                                                                  ;;
;; (add-hook 'display-line-numbers-mode-hook                                                                                                                                                                                                                             ;;
;;           (lambda ()                                                                                                                                                                                                                                                  ;;
;;             (setq display-line-numbers-width 4)))                                                                                                                                                                                                                     ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; toggle line wrap                                                                                                                                                                                                                                                   ;;
;; (setq compile-command "/usr/bin/python /usr/bin/scons")                                                                                                                                                                                                               ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (define-derived-mode scons-mode python-mode "scons"                                                                                                                                                                                                                   ;;
;;   "A python-mode for scons files")                                                                                                                                                                                                                                    ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (add-to-list 'auto-mode-alist '("SConstruct" . scons-mode))                                                                                                                                                                                                           ;;
;; (add-to-list 'auto-mode-alist '("SConscript" . scons-mode))                                                                                                                                                                                                           ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; expand region                                                                                                                                                                                                                                                      ;;
;; (require 'expand-region)                                                                                                                                                                                                                                              ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (global-set-key (kbd "C-S-SPC") 'er/expand-region)                                                                                                                                                                                                                    ;;
;; (global-set-key (kbd "C-SPC") (lambda()                                                                                                                                                                                                                               ;;
;;     "set-mark when nothing is selected"                                                                                                                                                                                                                               ;;
;;     (interactive)                                                                                                                                                                                                                                                     ;;
;;     (if (use-region-p)                                                                                                                                                                                                                                                ;;
;;         (er/contract-region 1)                                                                                                                                                                                                                                        ;;
;;       (call-interactively 'set-mark-command))))                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; compile mode                                                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;; ;; ansi                                                                                                                                                                                                                                                               ;;
;; (require 'ansi-color)  ;; buitin 28.1                                                                                                                                                                                                                                 ;;
;; (add-hook 'compilation-filter-hook 'ansi-color-compilation-filter)                                                                                                                                                                                                    ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (provide '.emacs)                                                                                                                                                                                                                                                     ;;
;; ;;; .emacs ends here                                                                                                                                                                                                                                                  ;;
;;                                                                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;;                                                                                                                                                                                                                                                                       ;;
;; (custom-set-variables                                                                                                                                                                                                                                                 ;;
;;  ;; custom-set-variables was added by Custom.                                                                                                                                                                                                                         ;;
;;  ;; If you edit it by hand, you could mess it up, so be careful.                                                                                                                                                                                                      ;;
;;  ;; Your init file should contain only one such instance.                                                                                                                                                                                                             ;;
;;  ;; If there is more than one, they won't work right.                                                                                                                                                                                                                 ;;
;;  '(column-number-mode t)                                                                                                                                                                                                                                              ;;
;;  '(custom-enabled-themes '(wombat))                                                                                                                                                                                                                                   ;;
;;  '(custom-safe-themes                                                                                                                                                                                                                                                 ;;
;;    '("10e330880269244ae45ae9e02fe6f55766da9e15036e7c7f07d7ce228195deb5"                                                                                                                                                                                               ;;
;;      "0f738dce3f831b6d64ee3e98052bdea663b74d5149dcbbf555327dcb4517fc08"                                                                                                                                                                                               ;;
;;      "749a7bb14efeb8b6c9b251c7a771ab7de500b247eb35f69bfccbdfca27e0602c"                                                                                                                                                                                               ;;
;;      "516ec39655c85f346393f5d93e0f03602b6bfc33335bf2fd673016c9c4cdc69e"                                                                                                                                                                                               ;;
;;      "0a8cf72fd94bfb67dd72dc085538b39ea47aeae8bfc2b8545c0d3c99c339c204"                                                                                                                                                                                               ;;
;;      "546f3e8c4cb46043df1f646322c4b57049fc4c31fdf96e41db077c3408660057"                                                                                                                                                                                               ;;
;;      "578002ec7093cedeb7d279794492b19ad7413cca3e16286e776168eb544798c4"                                                                                                                                                                                               ;;
;;      default))                                                                                                                                                                                                                                                        ;;
;;  '(display-battery-mode t)                                                                                                                                                                                                                                            ;;
;;  '(display-time-mode t)                                                                                                                                                                                                                                               ;;
;;  '(font-use-system-font t)                                                                                                                                                                                                                                            ;;
;;  '(indicate-buffer-boundaries '((top . left) (bottom . left) (up . left) (down . left)))                                                                                                                                                                              ;;
;;  '(indicate-empty-lines t)                                                                                                                                                                                                                                            ;;
;;  '(package-selected-packages                                                                                                                                                                                                                                          ;;
;;    '(ef-themes expand-region flycheck helm hungry-delete lsp-pyright                                                                                                                                                                                                  ;;
;;                lsp-ui magit night-owl-theme undo-tree web-mode                                                                                                                                                                                                        ;;
;;                yafolding))                                                                                                                                                                                                                                            ;;
;;  '(size-indication-mode t)                                                                                                                                                                                                                                            ;;
;;  '(tab-bar-mode t)                                                                                                                                                                                                                                                    ;;
;;  '(tool-bar-mode nil))                                                                                                                                                                                                                                                ;;
;; (custom-set-faces                                                                                                                                                                                                                                                     ;;
;;  ;; custom-set-faces was added by Custom.                                                                                                                                                                                                                             ;;
;;  ;; If you edit it by hand, you could mess it up, so be careful.                                                                                                                                                                                                      ;;
;;  ;; Your init file should contain only one such instance.                                                                                                                                                                                                             ;;
;;  ;; If there is more than one, they won't work right.                                                                                                                                                                                                                 ;;
;;  )                                                                                                                                                                                                                                                                    ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
